# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forms/fft_control.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_fftControl(object):
    def setupUi(self, fftControl):
        fftControl.setObjectName("fftControl")
        fftControl.resize(400, 202)
        fftControl.setCheckable(True)
        fftControl.setChecked(False)
        self.gridLayout_2 = QtWidgets.QGridLayout(fftControl)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(10, 10, 10, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(fftControl)
        self.label.setMaximumSize(QtCore.QSize(16777215, 10))
        self.label.setIndent(0)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 4, 0, 1, 1)
        self.title_line = QtWidgets.QLineEdit(fftControl)
        self.title_line.setMinimumSize(QtCore.QSize(0, 20))
        self.title_line.setMaximumSize(QtCore.QSize(16777215, 20))
        self.title_line.setObjectName("title_line")
        self.gridLayout.addWidget(self.title_line, 5, 0, 1, 1)
        self.fft_data_gbox = QtWidgets.QGroupBox(fftControl)
        self.fft_data_gbox.setCheckable(False)
        self.fft_data_gbox.setObjectName("fft_data_gbox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.fft_data_gbox)
        self.gridLayout_3.setContentsMargins(-1, 9, -1, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_4 = QtWidgets.QLabel(self.fft_data_gbox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.fft_data_gbox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.freq_min = QtWidgets.QSpinBox(self.fft_data_gbox)
        self.freq_min.setMaximumSize(QtCore.QSize(65, 16777215))
        self.freq_min.setMinimum(-150)
        self.freq_min.setMaximum(100)
        self.freq_min.setProperty("value", -150)
        self.freq_min.setObjectName("freq_min")
        self.gridLayout_3.addWidget(self.freq_min, 0, 1, 1, 1)
        self.freq_max = QtWidgets.QSpinBox(self.fft_data_gbox)
        self.freq_max.setMaximumSize(QtCore.QSize(65, 16777215))
        self.freq_max.setMinimum(-100)
        self.freq_max.setMaximum(150)
        self.freq_max.setProperty("value", 150)
        self.freq_max.setObjectName("freq_max")
        self.gridLayout_3.addWidget(self.freq_max, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.fft_data_gbox, 3, 0, 1, 3)
        self.label_3 = QtWidgets.QLabel(fftControl)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.line_width = QtWidgets.QDoubleSpinBox(fftControl)
        self.line_width.setDecimals(2)
        self.line_width.setMinimum(0.25)
        self.line_width.setMaximum(5.0)
        self.line_width.setSingleStep(0.25)
        self.line_width.setProperty("value", 0.5)
        self.line_width.setObjectName("line_width")
        self.gridLayout.addWidget(self.line_width, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(fftControl)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.common_graph = QtWidgets.QCheckBox(fftControl)
        self.common_graph.setText("")
        self.common_graph.setObjectName("common_graph")
        self.gridLayout.addWidget(self.common_graph, 0, 2, 1, 1)
        self.fft_plot_button = QtWidgets.QPushButton(fftControl)
        self.fft_plot_button.setObjectName("fft_plot_button")
        self.gridLayout.addWidget(self.fft_plot_button, 5, 2, 1, 1)
        self.fft_clear_button = QtWidgets.QPushButton(fftControl)
        self.fft_clear_button.setObjectName("fft_clear_button")
        self.gridLayout.addWidget(self.fft_clear_button, 5, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)

        self.retranslateUi(fftControl)
        QtCore.QMetaObject.connectSlotsByName(fftControl)

    def retranslateUi(self, fftControl):
        _translate = QtCore.QCoreApplication.translate
        fftControl.setWindowTitle(_translate("fftControl", "GroupBox"))
        self.label.setText(_translate("fftControl", "Plot title:"))
        self.fft_data_gbox.setTitle(_translate("fftControl", "Normalized frequency range"))
        self.label_4.setText(_translate("fftControl", "Min "))
        self.label_5.setText(_translate("fftControl", "Max "))
        self.label_3.setText(_translate("fftControl", "Line width [px]"))
        self.label_6.setText(_translate("fftControl", "Common graph"))
        self.fft_plot_button.setText(_translate("fftControl", "Plot"))
        self.fft_plot_button.setShortcut(_translate("fftControl", "P"))
        self.fft_clear_button.setText(_translate("fftControl", "Clear"))
        self.fft_clear_button.setShortcut(_translate("fftControl", "P"))
